########################################################
### Embedded Server  configuration  
### References-Doc:http://docs.spring.io/spring-boot/docs/1.5.3.RELEASE/reference/htmlsingle/#common-application-properties
########################################################
server:
       context-path: /
       port: 80
########################################################
### MYSQL Configuration  password encryption class DruidDecrypt.java
########################################################
spring:
       datasource:
                 type: com.alibaba.druid.pool.DruidDataSource
                 driver-class-name: com.mysql.jdbc.Driver
                 url: jdbc:mysql:///jeeshop?useUnicode=true&characterEncoding=UTF-8
                 username: root
                 password: hf96/2MU+Q12fdb9oZN9ghub1OHmUBa8YuW7NJf8Pll/sawcaRVscHTpr4t5SB39+KbJn31Lqy76uEDvj+sgMw==

########################################################
### DRUID Configuration
########################################################
                 filters: stat,wall,log4j,config
                 maxActive: 20
                 initialSize: 1
                 maxWait: 60000
                 minIdle: 10
                 maxIdle: 15
                 timeBetweenEvictionRunsMillis: 60000
                 minEvictableIdleTimeMillis: 300000
                 validationQuery: SELECT 'x'
                 testWhileIdle: true
                 testOnBorrow: false
                 testOnReturn: false
                 maxOpenPreparedStatements: 20
                 removeAbandoned: true
                 removeAbandonedTimeout: 1800
                 logAbandoned: true
                 connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true

########################################################
### SPRING Boot Redis Configuration
########################################################
       redis:
           host: 127.0.0.1
           password:
           port: 6379
           timeout: 0
           ssl: false
           pool:
                max-active: 8
                max-idle: 200
                max-wait: -1
                min-idle: 1
########################################################
###       FREEMARKER Configuration
########################################################

       freemarker:
                  prefix: 
                  suffix: .ftl
                  template-loader-path: /WEB-INF/templates/,/WEB-INF/templates/front/
                  allow-request-override: false
                  cache: false
                  check-template-location: true
                  charset: UTF-8
                  content-type: text/html
                  expose-request-attributes: false
                  expose-session-attributes: false
                  expose-spring-macro-helpers: false
                  request-context-attribute: request
                  settings:
                           number_format: #.##
                           date_format: yyyy-MM-dd
                           time_format: HH:mm:ss
                           datetime_format: yyyy-MM-dd HH:mm:ss
                           default_encoding: utf-8
                           url_escaping_charset: utf-8
                           auto_import: /import/env.ftl as env, /import/i18n.ftl as i18n, /import/keyvalue.ftl as KV
mybatis:
  mapper-locations: classpath*:com/zlkj/ssm/shop/**/mapper/sql/xml/*.xml
  config-location: classpath:config/mybatis/mybatis-config.xml